services:
  mysql:
    container_name: 'books-manager-mysql'
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=books_app_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'